### ISSUE TITLE
Tab AutoComplete in PowerShell

### ISSUE THREAD

**Issue by jungerm2** [magic-wormhole/magic-wormhole#416]
It seems that tab autocomplete does not work in PowerShell in win10. The error seems to stem from the `readline` package which isn't supposed to work on Windows.

Is this expected behavior, how can I get tab autocomplete in PowerShell to work? or did I miss something? Here's the traceback:

```
> wormhole receive
Enter receive wormhole code: 8-gradcompleter exception: module 'readline' has no attribute 'get_completion_type'
Traceback (most recent call last):
  File "c:\users\miniconda3\lib\site-packages\wormhole\_rlcompleter.py", line 45, in completer
    return self._wrapped_completer(text, state)
  File "c:\users\miniconda3\lib\site-packages\wormhole\_rlcompleter.py", line 56, in _wrapped_completer
    ct = readline.get_completion_type()
AttributeError: module 'readline' has no attribute 'get_completion_type'
Readline internal error
Traceback (most recent call last):
  File "c:\users\miniconda3\lib\site-packages\pyreadline\console\console.py", line 768, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
  File "c:\users\miniconda3\lib\site-packages\pyreadline\rlmain.py", line 571, in readline
    self._readline_from_keyboard()
  File "c:\users\miniconda3\lib\site-packages\pyreadline\rlmain.py", line 536, in _readline_from_keyboard
    if self._readline_from_keyboard_poll():
  File "c:\users\miniconda3\lib\site-packages\pyreadline\rlmain.py", line 556, in _readline_from_keyboard_poll
    result = self.mode.process_keyevent(event.keyinfo)
  File "c:\users\miniconda3\lib\site-packages\pyreadline\modes\emacs.py", line 243, in process_keyevent
    r = self.process_keyevent_queue[-1](keyinfo)
  File "c:\users\miniconda3\lib\site-packages\pyreadline\modes\emacs.py", line 286, in _process_keyevent
    r = dispatch_func(keyinfo)
  File "c:\users\miniconda3\lib\site-packages\pyreadline\modes\basemode.py", line 257, in complete
    completions = self._get_completions()
  File "c:\users\miniconda3\lib\site-packages\pyreadline\modes\basemode.py", line 200, in _get_completions
    r = self.completer(ensure_unicode(text), i)
  File "c:\users\miniconda3\lib\site-packages\wormhole\_rlcompleter.py", line 45, in completer
    return self._wrapped_completer(text, state)
  File "c:\users\miniconda3\lib\site-packages\wormhole\_rlcompleter.py", line 56, in _wrapped_completer
    ct = readline.get_completion_type()
AttributeError: module 'readline' has no attribute 'get_completion_type'
ERROR:  The key you entered contains spaces or was missing a dash.
Magic-wormhole expects the numerical nameplate and the code words to
be separated by dashes. Please reenter the key you were given
separating the words with dashes.

incomplete wormhole code

Command interrupted: please press Return to quit
```

Thanks!

**Comment by warner** [comment]
I think your analysis is correct. We use `readline` for the tab completion, so if it doesn't provide that feature on a given platform, we don't have any fallback mechanism.

I know that some platforms (/me glares at macOS) use a subset of GNU Readline called `libedit`, that provides most of the editing functionality but not the completion logic. I wouldn't be surprised if the windows world (or some interaction between PowerShell and readline/libedit) is running into something like this.

If someone who knows the windows+readline world has an idea on what we could do to enable this, that'd be awesome!

**Comment by jungerm2** [comment]
Closing as this error seems to have been resolved. However, while it no longer throws an error, it also does not auto-complete which might be a separate issue.
