### ISSUE TITLE
Homebrewed Wormhole on an M1 not working

### ISSUE THREAD

**Issue by anttivs** [magic-wormhole/magic-wormhole#451]
I have installed Wormhole on an M1 Mac (macOS 12.6 Monterey) both directly and from source

`brew install --build-from-source magic-wormhole` 
`brew install magic-wormhole`

Running wormhole fails similarly in both cases:

```
➜  ~ wormhole receive 67-hideaway-adrift
Traceback (most recent call last):
  File "/opt/homebrew/bin/wormhole", line 33, in <module>
    sys.exit(load_entry_point('magic-wormhole==0.12.0', 'console_scripts', 'wormhole')())
  File "/opt/homebrew/bin/wormhole", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/wormhole/__init__.py", line 1, in <module>
    from ._rlcompleter import input_with_completion
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/wormhole/_rlcompleter.py", line 8, in <module>
    from twisted.internet.defer import inlineCallbacks, returnValue
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/twisted/internet/defer.py", line 44, in <module>
    from twisted.internet.interfaces import IDelayedCall, IReactorTime
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/twisted/internet/interfaces.py", line 26, in <module>
    from twisted.python.failure import Failure
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/twisted/python/__init__.py", line 9, in <module>
    from .deprecate import deprecatedModuleAttribute
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/twisted/python/deprecate.py", line 755, in <module>
    ) -> Callable[[_Tc], _Tc]:
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/typing.py", line 875, in __getitem__
    return self.__getitem_inner__(params)
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/typing.py", line 265, in inner
    return cached(*args, **kwds)
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/typing.py", line 888, in __getitem_inner__
    return self.copy_with(params)
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/typing.py", line 860, in copy_with
    return _CallableGenericAlias(self.__origin__, params,
  File "/Users/avs/Applications/QGIS.app/Contents/Resources/python/typing.py", line 729, in __init__
    self.__parameters__ = _collect_type_vars(params)
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/typing_extensions.py", line 136, in _collect_type_vars
    if _should_collect_from_parameters(t):
  File "/opt/homebrew/Cellar/magic-wormhole/0.12.0_7/libexec/lib/python3.10/site-packages/typing_extensions.py", line 110, in _should_collect_from_parameters
    t, (typing._GenericAlias, _types.GenericAlias, _types.UnionType)
AttributeError: module 'types' has no attribute 'UnionType'. Did you mean: 'FunctionType'?
```

**Comment by anttivs** [comment]
And now I see the problem, which is a borked Python installation.
