### ISSUE TITLE
Error using wormhole receive

### ISSUE THREAD

**Issue by Risto-Stevcev** [magic-wormhole/magic-wormhole#463]
Using void linux
```
[~]λ wormhole receive                                                                                                                   
Traceback (most recent call last):                                                                                                      
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/cli/cli.py", line 255, in <lambda>                                     
    return react(_dispatch_command, (cfg, lambda: f(cfg)))                                                                              
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/cli/cmd_receive.py", line 49, in receive                               
    d = r.go()                                                                                                                          
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator                                     
    return _cancellableInlineCallbacks(gen)                                                                                             
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks                         
    _inlineCallbacks(None, gen, status)                                                                                                 
--- <exception caught here> ---                                                                                                         
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command                            
    yield maybeDeferred(command)                                                                                                        
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks                                    
    result = current_context.run(gen.send, result)                                                                                      
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/cli/cmd_receive.py", line 81, in go                                    
    w = create(                                                                                                                         
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/wormhole.py", line 290, in create                                      
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,                                                              
  File "<attrs generated init wormhole._boss.Boss>", line 23, in __init__                                                               
    self.__attrs_post_init__()                                                                                                          
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/_boss.py", line 52, in __attrs_post_init__                             
    self._build_workers()                                                                                                               
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/_boss.py", line 62, in _build_workers                                  
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/home/risto/.local/lib/python3.11/site-packages/wormhole/_rendezvous.py", line 87, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated, 
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
builtins.TypeError: code() argument 13 must be str, not int
ERROR: code() argument 13 must be str, not int
[~]λ python --version
Python 3.11.0
```

**Comment by meejah** [comment]
Hmm, this looks pretty low-level so might be related to more general "python 3.11".

**Comment by meejah** [comment]
I added Python 3.10 and 3.11 to the CI test-matrix, but all tests pass.

How did you install this?

**Comment by meejah** [comment]
I tried with Python 3.11.0 as installed by `pyenv` and `wormhole receive` runs as expected

**Comment by nissaofthesea** [comment]
also experiencing this with void linux, both `wormhole send` and `wormhole receive`.

```console
$ wormhole send
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 255, in <lambda>
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_send.py", line 38, in send
    return Sender(args, reactor).go()
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_send.py", line 66, in go
    w = create(
  File "/usr/lib/python3.11/site-packages/wormhole/wormhole.py", line 290, in create
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,
  File "<attrs generated init wormhole._boss.Boss>", line 23, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 52, in __attrs_post_init__
    self._build_workers()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 62, in _build_workers
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_rendezvous.py", line 87, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
builtins.TypeError: code() argument 13 must be str, not int
ERROR: code() argument 13 must be str, not int
```

```console
$ wormhole receive
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 255, in <lambda>
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_receive.py", line 49, in receive
    d = r.go()
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/usr/lib/python3.11/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/lib/python3.11/site-packages/wormhole/cli/cmd_receive.py", line 81, in go
    w = create(
  File "/usr/lib/python3.11/site-packages/wormhole/wormhole.py", line 290, in create
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,
  File "<attrs generated init wormhole._boss.Boss>", line 23, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 52, in __attrs_post_init__
    self._build_workers()
  File "/usr/lib/python3.11/site-packages/wormhole/_boss.py", line 62, in _build_workers
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3.11/site-packages/wormhole/_rendezvous.py", line 87, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/usr/lib/python3.11/site-packages/twisted/application/internet.py", line 1168, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
builtins.TypeError: code() argument 13 must be str, not int
ERROR: code() argument 13 must be str, not int
```

i installed this with the system package manager `xbps`.
this might be an issue that needs to be taken to the void package's maintainer(s), if `wormhole` is working elsewhere.

```console
$ xbps-query magic-wormhole
architecture: x86_64
filename-sha256: 69a20103021763458e9d9d32822c560bb5b6989c845256dfc7477b7b060a1dbe
filename-size: 146KB
homepage: https://magic-wormhole.readthedocs.io/en/latest/
install-date: 2022-11-09 04:58 UTC
install-script: 849B
installed_size: 757KB
license: MIT
maintainer: travankor <travankor@tuta.io>
metafile-sha256: 0999636f20a86556e26fc15349fcb20a1d24cad23b0662dc3311382be0afc3e8
pkgname: magic-wormhole
pkgver: magic-wormhole-0.12.0_5
remove-script: 847B
repository: https://repo-default.voidlinux.org/current
run_depends:
	python3-autobahn>=0
	python3-cffi>=0
	python3-click>=0
	python3-humanize>=0
	python3-idna>=0
	python3-pynacl>=0
	python3-service_identity>=0
	python3-spake2>=0
	python3-tqdm>=0
	python3-txtorcon>=0
short_desc: Get things from one computer to another, safely
source-revisions: magic-wormhole:baa8a5a20a
state: installed
```

**Comment by meejah** [comment]
Yeah, I would assume this is a void-linux issue; can you open a bug there and report back here please? (I don't know much about void linux).

**Comment by nissaofthesea** [comment]
this issue is now resolved on my end, as of https://github.com/void-linux/void-packages/pull/40446 (https://github.com/void-linux/void-packages/issues/40487#issuecomment-1312500658)

**Comment by Risto-Stevcev** [comment]
Confirmed that it's working now after pulling latest updates from void
