### ISSUE TITLE
Tab completion for nameplates gives error

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole#471]
I tried out the tab completion of nameplates for fun and ran into an error.

1. `wormhole receive`
2. Type a digit then tab, try a few times until it completes
3. Erase the completed bit, type a digit and press tab again

```
Enter receive wormhole code: 4completer exception: nameplate (1-) already entered, cannot go back
Traceback (most recent call last):
  File "/nix/store/vshzbil4ps6rybwljfi3swwg2w2x0ihi-python3.10-magic-wormhole-0.12.0/lib/python3.10/site-packages/wormhole/_rlcompleter.py", line 45, in completer
    return self._wrapped_completer(text, state)
  File "/nix/store/vshzbil4ps6rybwljfi3swwg2w2x0ihi-python3.10-magic-wormhole-0.12.0/lib/python3.10/site-packages/wormhole/_rlcompleter.py", line 59, in _wrapped_completer
    self._matches = self._commit_and_build_completions(text)
  File "/nix/store/vshzbil4ps6rybwljfi3swwg2w2x0ihi-python3.10-magic-wormhole-0.12.0/lib/python3.10/site-packages/wormhole/_rlcompleter.py", line 94, in _commit_and_build_completions
    raise AlreadyInputNameplateError(
wormhole.errors.AlreadyInputNameplateError: nameplate (1-) already entered, cannot go back
```

In general I am increasingly convinced that this entire feature should just be removed, as it involves quite a bit of complexity without really improving the user experience. Think about it, how often have you used it yourself? (Tbf I think it *could* be made worthwhile having so that users would actually use it, but that would require even more effort)

**Comment by meejah** [comment]
I use tab-completion on the "words" part all the time .. so just clarifying if you mean "remove tab-completion" or just "remove tab-completion of the nameplate part only"...?

(It _could_ use something else for the UX in non-CLI applications but I do agree that its utility isn't great for the nameplate part itself in the CLI)

**Comment by piegamesde** [comment]
This issue is about the nameplate completion only.

**Comment by meejah** [comment]
I agree the utility of the nameplate portion of tab-completion is .. definitely far _less_ useful than the rest.

Additionally (off the top of my head):

- the nameplate completion depends on the `list` command, which makes DoS easier (for example)
- word-list internationalization probably wants `mailbox` (and _not_ `nameplate`) attributes for security reasons (so can't use `list` anyway)
- from the above stack-trace it _appears_ at least this client already needs you to "commit" to a nameplate fairly early anyway

Perhaps there are other reasons to add (either for or against) but I would put all of the above in the "reasons to remove nameplate completion" column :)

**Comment by vu3rdd** [comment]
I too use tab-completion mostly for the words and it is very useful. I agree, nameplate completion and commitment is far less useful as a user.
