### ISSUE TITLE
Error using wormhole receive

### ISSUE THREAD

**Issue by new-gen23** [magic-wormhole/magic-wormhole#474]
Similar to https://github.com/magic-wormhole/magic-wormhole/issues/463, I encountered the same problem today.
python --version  
Python 3.11.2

wormhole --version  
magic-wormhole 0.12.0

Debian Unstable

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wormhole/cli/cli.py", line 255, in <lambda>
    return react(_dispatch_command, (cfg, lambda: f(cfg)))
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 49, in receive
    d = r.go()
  File "/home/user/.local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1909, in unwindGenerator
    return _cancellableInlineCallbacks(gen)  # type: ignore[unreachable]
  File "/home/user/.local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/wormhole/cli/cli.py", line 122, in _dispatch_command
    yield maybeDeferred(command)
  File "/home/user/.local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/lib/python3/dist-packages/wormhole/cli/cmd_receive.py", line 81, in go
    w = create(
  File "/usr/lib/python3/dist-packages/wormhole/wormhole.py", line 290, in create
    b = Boss(w, side, relay_url, appid, wormhole_versions, client_version,
  File "<attrs generated init wormhole._boss.Boss>", line 23, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3/dist-packages/wormhole/_boss.py", line 52, in __attrs_post_init__
    self._build_workers()
  File "/usr/lib/python3/dist-packages/wormhole/_boss.py", line 62, in _build_workers
    self._RC = RendezvousConnector(self._url, self._appid, self._side,
  File "<attrs generated init wormhole._rendezvous.RendezvousConnector>", line 18, in __init__
    self.__attrs_post_init__()
  File "/usr/lib/python3/dist-packages/wormhole/_rendezvous.py", line 87, in __attrs_post_init__
    d = self._connector.whenConnected(failAfterFailures=faf)
  File "/home/user/.local/lib/python3.11/site-packages/twisted/application/internet.py", line 1169, in whenConnected
    return self._machine.whenConnected(failAfterFailures)
  File "/home/user/.local/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
    @preserveName(self.method)
  File "/home/user/.local/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
    return copyfunction(decorated,
  File "/home/user/.local/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
    return function(copycode(template.__code__, codechanges), *values)
  File "/home/user/.local/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    return code(*values)
builtins.TypeError: code() argument 13 must be str, not int
ERROR: code() argument 13 must be str, not int
```

**Comment by meejah** [comment]
Can you say how you installed this? (From the paths it looks like probably `pip install --local magic-wormhole`...?)

**Comment by new-gen23** [comment]
`apt-get install magic wormhole`
The path is where apt installs it. I made sure everything vom pip regarding wormhole is purged.

**Comment by meejah** [comment]
Are you sure you didn't (also!) install with `pip --user ...`? Or, did you maybe install some other Twisted and/or Automat using thing with `pip --user`? It seems to be picking at least those up from an odd spot.

I'm asking all that because `~user/.local/...` is a weird spot for Debian to install anything (and on my Debian testing system it installs to `/usr/bin/wormhole`). Note that the settings for `PYTHONPATH` in your current shell could impact this since `/usr/bin/wormhole` is "just a Python script" itself...

**Comment by new-gen23** [comment]
Sorry, I was busy and hoping a few updates would solve the problem. Current status:

- APT installs magic-wormhole_0.12.0-1.1_all.deb
- pip list | grep -i wormhole returns: 0.12.0
- When magic-wormhole is purged via apt, pip list also returns nothing
- magic-wormhole binary  is installed in /usr/bin/wormhole
- PYTHONPATH is not modified. export PYTHONPATH returns nothing.

**Comment by new-gen23** [comment]
Problem solved.  
I manually removed:  
~user/.local/lib/python3.11/site-packages/automat/
Afterwards, magic-wormhole simply runs smoothly. Thanks.
