### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [magic-wormhole/magic-wormhole#509]
While trying to migrate zurl to test against py3.12, ran into the following test failure

```
/private/tmp/magic-wormhole--spake2-20231029-6748-d23kmi/spake2-0.8/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/private/tmp/magic-wormhole--spake2-20231029-6748-d23kmi/spake2-0.8/setup.py", line 62, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6748-d23kmi/spake2-0.8/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6748-d23kmi/spake2-0.8/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6748-d23kmi/spake2-0.8/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
error: subprocess-exited-with-error
```

log, https://github.com/Homebrew/homebrew-core/actions/runs/6685443985/job/18163767072
relates to https://github.com/Homebrew/homebrew-core/pull/152753

**Comment by chenrui333** [comment]
looks like it got fixed, https://github.com/warner/python-spake2/pull/15
