### ISSUE TITLE
```wormhole send``` fails in freebsd-14.1-p1 with ModuleNotFoundError,pkg:py39-magic-wormhole

### ISSUE THREAD

**Issue by polyduekes-git** [magic-wormhole/magic-wormhole#530]
i am not really sure if this is the right place to report but since this was listed as www for the py-magic-wormhole port, so sorry if i created the issue at the wrong place and i will really appreciate if i could get to know the right place to report
whenever i do ```wormhole send```(doesn't matter if it is a directory or file) the command fails with the following output:-
```
Traceback (most recent call last):
  File "/usr/local/bin/wormhole", line 33, in <module>
    sys.exit(load_entry_point('magic-wormhole==0.14.0', 'console_scripts', 'wormhole')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wormhole/cli/cli.py", line 282, in send
    from . import cmd_send
  File "/usr/local/lib/python3.9/site-packages/wormhole/cli/cmd_send.py", line 21, in <module>
    from iterableio import open_iterable
ModuleNotFoundError: No module named 'iterableio'
```
i would really appreciate any feedback, thank you

**Comment by pR0Ps** [comment]
From the error message, it looks like the port doesn't include the [iterable-io](https://pypi.org/project/iterable-io/) or [zipstream-ng](https://pypi.org/project/zipstream-ng/) dependencies that I added in #503 .

Without knowing much about how FreeBSD ports work, I would expect that they would have to be packaged and added to https://cgit.freebsd.org/ports/tree/net/py-magic-wormhole/Makefile for the port to be able to use them.

**Comment by njthomas** [comment]
bugs.freebsd.org has #[279304](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279304) opened for this. A fix has yet to be submitted.

**Comment by meejah** [comment]
(Asked at the FreeBSD tracker too: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279304)

Is there some easy-ish tool that I could use in future to gauge how much work we might be making for downstream packagers (when inevitably in the future we consider a new dependency)?

**Comment by njthomas** [comment]
> Is there some easy-ish tool that I could use in future to gauge how much work we might be making for downstream packagers (when inevitably in the future we consider a new dependency)?

Honestly, more than any tool, I think the best thing is to **create a mailing list for all package maintainers**, invite them all to subscribe, and give them a heads up whenever you will be adding new dependencies or will be making breaking changes.

_(The amount of notification time you should give them is sort of variable, use your best judgement.)_

**Comment by meejah** [comment]
I do announce releases when they happen on the Python mailing-list. It seems like one thing that could be improved would be to specifically call out dependency changes.

e.g. 0.14.0 was announced here: https://mail.python.org/pipermail/python-list/2024-April/912199.html and although it does say that "streaming" is now supported, it neglects to point out this comes with a new dependency...

If these details were also included, would the above work? Or did you mean a more-targeted "just magic-wormhole" list?
